#!/usr/bin/env python3
"""
Kill switch registry for phantom-mcp.
Auto-generated by ai-agent-kill-switch-and-graduated-response scaffold.
Register at agent startup; call terminate() from the graduated response controller.
"""
import json
import os
import signal
import datetime
from pathlib import Path

REGISTRY_PATH = Path(os.environ.get("KILL_REGISTRY_PATH",
                                    "/tmp/phantom-mcp-kill-registry.json"))


class KillSwitchRegistry:
    def __init__(self, credentials_to_revoke: list):
        self.agent_id = "phantom-mcp"
        self.pid = os.getpid()
        self.credentials_to_revoke = credentials_to_revoke
        self._throttled = False

    def register(self) -> None:
        REGISTRY_PATH.parent.mkdir(parents=True, exist_ok=True)
        REGISTRY_PATH.write_text(json.dumps({
            "agent_id": self.agent_id,
            "pid": self.pid,
            "started_at": datetime.datetime.utcnow().isoformat(),
            "credentials_to_revoke": self.credentials_to_revoke,
            "shutdown_endpoint": "http://localhost:8080/admin/shutdown",
            "throttled": False,
        }, indent=2))

    def deregister(self) -> None:
        REGISTRY_PATH.unlink(missing_ok=True)

    def is_throttled(self) -> bool:
        return self._throttled

    def throttle(self, reason: str) -> dict:
        self._throttled = True
        event = {
            "action": "THROTTLED",
            "agent_id": self.agent_id,
            "reason": reason,
            "timestamp": datetime.datetime.utcnow().isoformat(),
        }
        if REGISTRY_PATH.exists():
            data = json.loads(REGISTRY_PATH.read_text())
            data.update({"throttled": True, "throttle_reason": reason,
                          "throttle_time": event["timestamp"]})
            REGISTRY_PATH.write_text(json.dumps(data, indent=2))
        return event

    def terminate(self, reason: str, autonomous: bool = False) -> dict:
        event = {
            "action": "TERMINATED",
            "agent_id": self.agent_id,
            "pid": self.pid,
            "reason": reason,
            "autonomous": autonomous,
            "timestamp": datetime.datetime.utcnow().isoformat(),
        }
        self._revoke_credentials()
        self.deregister()
        os.kill(self.pid, signal.SIGTERM)
        return event

    def _revoke_credentials(self) -> None:
        """Rotate the Phantom API key in Secrets Manager so all existing tokens are invalid."""
        import secrets as _secrets
        try:
            import boto3
            client = boto3.client("secretsmanager", region_name="us-east-1")
            for secret_id in self.credentials_to_revoke:
                new_value = _secrets.token_urlsafe(40)
                client.put_secret_value(SecretId=secret_id, SecretString=new_value)
                print(f"[kill-switch] Rotated secret: {secret_id}")
        except Exception as exc:
            # Never let revocation failure prevent process termination
            print(f"[kill-switch] WARNING: credential revocation failed ({exc}) — terminating anyway")
