#!/usr/bin/env python3
"""
AI Agent Kill Switch and Graduated Response Agent

Scaffolds, tests, and simulates the three-level graduated containment response
system for AI agents.

Subcommands:
  scaffold  — Generate kill switch implementation files for an agent service
  test      — Test a kill switch against a running agent (staging use only)
  simulate  — Simulate graduated response signal combinations and show which
              level fires
  audit     — Audit an existing agent service for kill switch readiness

Usage:
    agent.py scaffold --agent-id ew-agent --port 8001 --output ./generated/
    agent.py test     --registry /var/run/agent/kill_registry.json --dry-run
    agent.py simulate --signals injection_high,external_endpoint_called
    agent.py audit    --service-path ./ew-agent/

Exit codes:
    0 — kill switch present and test passed / simulation non-critical
    1 — kill switch absent, test failed, or Level 3 dual signal confirmed
"""

import argparse
import json
import os
import sys
import re
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Signal definitions
# ---------------------------------------------------------------------------

SIGNALS = {
    "injection_high_confidence": {
        "label": "High-confidence prompt injection detected",
        "level": 1,
        "can_pair_for_level3": True,
        "pair_signals": ["external_endpoint_called"],
    },
    "external_endpoint_called": {
        "label": "Agent called an external (non-allowlisted) endpoint",
        "level": 1,
        "can_pair_for_level3": True,
        "pair_signals": ["injection_high_confidence"],
    },
    "rate_anomaly_10x": {
        "label": "Write rate 10x above baseline",
        "level": 2,
        "auto_action": "throttle",
        "can_pair_for_level3": False,
    },
    "rate_anomaly_50x": {
        "label": "Write rate 50x above baseline",
        "level": 2,
        "auto_action": "throttle",
        "can_pair_for_level3": False,
    },
    "injection_low_confidence": {
        "label": "Low-confidence injection pattern logged",
        "level": 1,
        "auto_action": "log_and_alert",
        "can_pair_for_level3": False,
    },
    "unauthorized_subprocess": {
        "label": "Unauthorized subprocess spawned",
        "level": 2,
        "auto_action": "throttle",
        "can_pair_for_level3": True,
        "pair_signals": ["external_endpoint_called", "injection_high_confidence"],
    },
    "reward_hacking": {
        "label": "Optimization/quality metric divergence (reward hacking signal)",
        "level": 2,
        "auto_action": "throttle",
        "can_pair_for_level3": False,
    },
    "kill_switch_disabled_attempt": {
        "label": "Agent attempted to disable its own monitor",
        "level": 3,
        "auto_action": "kill",
        "can_pair_for_level3": False,
        "standalone_kill": True,
    },
}

DUAL_SIGNAL_PAIRS = [
    ("injection_high_confidence", "external_endpoint_called"),
    ("unauthorized_subprocess", "external_endpoint_called"),
    ("unauthorized_subprocess", "injection_high_confidence"),
]

LEVEL_ACTIONS = {
    1: "LOG + ALERT on-call. Agent keeps running. Human decides.",
    2: "THROTTLE — pause new tool calls. Human has 5-min window to intervene.",
    3: "KILL — terminate process, revoke credentials. Human notified immediately.",
}

# ---------------------------------------------------------------------------
# Audit patterns
# ---------------------------------------------------------------------------

KILL_SWITCH_PATTERNS = [
    r"os\.kill\s*\(",
    r"signal\.SIGTERM",
    r"kill_registry",
    r"KillSwitch",
    r"/admin/shutdown",
    r"SIGTERM",
]

THROTTLE_PATTERNS = [
    r"throttle",
    r"is_throttled",
    r"THROTTLED",
]

REGISTRATION_PATTERNS = [
    r"register_agent",
    r"kill_registry\.json",
    r"KILL_REGISTRY",
]

ENDPOINT_PATTERNS = [
    r"@.*router.*post.*shutdown",
    r"@.*app.*post.*shutdown",
    r"/admin/shutdown",
]


# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

def cmd_scaffold(args: argparse.Namespace) -> int:
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)

    agent_id = args.agent_id
    port = args.port

    # kill_switch.py
    kill_switch_code = f'''#!/usr/bin/env python3
"""
Kill switch registry for {agent_id}.
Auto-generated by ai-agent-kill-switch-and-graduated-response scaffold.
Register at agent startup; call terminate() from the graduated response controller.
"""
import json
import os
import signal
import datetime
from pathlib import Path

REGISTRY_PATH = Path(os.environ.get("KILL_REGISTRY_PATH",
                                    "/var/run/{agent_id}/kill_registry.json"))


class KillSwitchRegistry:
    def __init__(self, credentials_to_revoke: list):
        self.agent_id = "{agent_id}"
        self.pid = os.getpid()
        self.credentials_to_revoke = credentials_to_revoke
        self._throttled = False

    def register(self) -> None:
        REGISTRY_PATH.parent.mkdir(parents=True, exist_ok=True)
        REGISTRY_PATH.write_text(json.dumps({{
            "agent_id": self.agent_id,
            "pid": self.pid,
            "started_at": datetime.datetime.utcnow().isoformat(),
            "credentials_to_revoke": self.credentials_to_revoke,
            "shutdown_endpoint": "http://localhost:{port}/admin/shutdown",
            "throttled": False,
        }}, indent=2))

    def deregister(self) -> None:
        REGISTRY_PATH.unlink(missing_ok=True)

    def is_throttled(self) -> bool:
        return self._throttled

    def throttle(self, reason: str) -> dict:
        self._throttled = True
        event = {{
            "action": "THROTTLED",
            "agent_id": self.agent_id,
            "reason": reason,
            "timestamp": datetime.datetime.utcnow().isoformat(),
        }}
        if REGISTRY_PATH.exists():
            data = json.loads(REGISTRY_PATH.read_text())
            data.update({{"throttled": True, "throttle_reason": reason,
                          "throttle_time": event["timestamp"]}})
            REGISTRY_PATH.write_text(json.dumps(data, indent=2))
        return event

    def terminate(self, reason: str, autonomous: bool = False) -> dict:
        event = {{
            "action": "TERMINATED",
            "agent_id": self.agent_id,
            "pid": self.pid,
            "reason": reason,
            "autonomous": autonomous,
            "timestamp": datetime.datetime.utcnow().isoformat(),
        }}
        self._revoke_credentials()
        self.deregister()
        os.kill(self.pid, signal.SIGTERM)
        return event

    def _revoke_credentials(self) -> None:
        # TODO: implement revocation via your secrets manager
        # Example: vault.revoke_token(os.environ[cred]) or
        #          boto3.client("secretsmanager").delete_secret(SecretId=cred)
        for cred in self.credentials_to_revoke:
            print(f"[kill-switch] Revoking credential: {{cred}}")
'''
    (output / "kill_switch.py").write_text(kill_switch_code)

    # graduated_response.py
    graduated_code = f'''#!/usr/bin/env python3
"""
Graduated response controller for {agent_id}.
Wire on_injection_detected(), on_rate_anomaly(), on_external_endpoint_called()
into your existing guardrails. Never auto-kill on a single signal.
"""
from datetime import datetime, timezone
from .kill_switch import KillSwitchRegistry

LEVEL2_AUTO_THROTTLE_FACTOR = 10
LEVEL3_DUAL_SIGNAL_WINDOW_S = 60


class GraduatedResponseController:
    def __init__(self, kill_switch: KillSwitchRegistry, notifier):
        self._ks = kill_switch
        self._notifier = notifier
        self._injection_at = None
        self._external_at = None
        self._active_level = 0

    def on_injection_detected(self, confidence: str, detail: str) -> None:
        if confidence == "HIGH":
            self._injection_at = datetime.now(timezone.utc)
            self._level1(f"High-confidence injection: {{detail[:100]}}")
            self._check_dual_signal()
        else:
            self._level1(f"Low-confidence injection logged: {{detail[:100]}}")

    def on_rate_anomaly(self, actual: int, baseline: float) -> None:
        factor = actual / baseline if baseline > 0 else float("inf")
        if factor >= LEVEL2_AUTO_THROTTLE_FACTOR:
            self._level2(f"Write rate {{factor:.1f}}x above baseline")
        else:
            self._level1(f"Write rate elevated: {{factor:.1f}}x above baseline")

    def on_external_endpoint_called(self, url: str) -> None:
        self._external_at = datetime.now(timezone.utc)
        self._level1(f"External endpoint called: {{url}}")
        self._check_dual_signal()

    def human_throttle(self, reason: str) -> dict:
        return self._ks.throttle(reason=reason)

    def human_kill(self, reason: str) -> dict:
        return self._ks.terminate(reason=reason, autonomous=False)

    def _level1(self, detail: str) -> None:
        self._notifier.alert(level=1, detail=detail)

    def _level2(self, detail: str) -> None:
        if self._active_level < 2:
            self._active_level = 2
            event = self._ks.throttle(reason=detail)
            self._notifier.alert(level=2, detail=detail, event=event)

    def _level3(self, detail: str, autonomous: bool) -> None:
        if self._active_level < 3:
            self._active_level = 3
            event = self._ks.terminate(reason=detail, autonomous=autonomous)
            self._notifier.alert(level=3, detail=detail, event=event)

    def _check_dual_signal(self) -> None:
        if self._injection_at is None or self._external_at is None:
            return
        delta = abs((self._injection_at - self._external_at).total_seconds())
        if delta <= LEVEL3_DUAL_SIGNAL_WINDOW_S:
            self._level3(
                detail=f"Dual signal within {{delta:.0f}}s: injection + external endpoint",
                autonomous=True,
            )
'''
    (output / "graduated_response.py").write_text(graduated_code)

    # kill_agent.py (operator script)
    kill_script = f'''#!/usr/bin/env python3
"""
Emergency kill script for {agent_id}.
Pre-written for runbook use — do NOT modify during an incident.
Usage:
    ADMIN_SHUTDOWN_TOKEN=<token> python kill_agent.py --reason "..."
    ADMIN_SHUTDOWN_TOKEN=<token> python kill_agent.py --throttle --reason "..."
"""
import argparse, json, os, signal, sys, datetime, urllib.request, hmac
from pathlib import Path

REGISTRY_PATH = Path(os.environ.get("KILL_REGISTRY_PATH",
                                    "/var/run/{agent_id}/kill_registry.json"))

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--reason", required=True)
    parser.add_argument("--throttle", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not REGISTRY_PATH.exists():
        print(f"ERROR: Registry not found — is {{REGISTRY_PATH}} present?", file=sys.stderr)
        sys.exit(1)

    registry = json.loads(REGISTRY_PATH.read_text())
    pid = registry["pid"]
    endpoint = registry.get("shutdown_endpoint", "http://localhost:{port}/admin/shutdown")
    token = os.environ.get("ADMIN_SHUTDOWN_TOKEN", "")

    ts = datetime.datetime.utcnow().isoformat()
    print(f"[{{ts}}] Targeting {agent_id} (PID {{pid}})")
    print(f"Reason : {{args.reason}}")
    print(f"Action : {{'THROTTLE' if args.throttle else 'KILL'}}")
    if args.dry_run:
        print("[DRY RUN] No action taken.")
        return

    action = "throttle" if args.throttle else "shutdown"
    url = endpoint.replace("/shutdown", f"/{{action}}") + f"?reason={{args.reason}}"
    req = urllib.request.Request(url, method="POST",
                                  headers={{"X-Admin-Token": token}})
    try:
        urllib.request.urlopen(req, timeout=10)
        print(f"HTTP {{action}} sent successfully.")
    except Exception as e:
        print(f"HTTP endpoint failed ({{e}}), falling back to SIGTERM")
        if not args.throttle:
            try:
                os.kill(pid, signal.SIGTERM)
                print(f"SIGTERM sent to PID {{pid}}")
            except ProcessLookupError:
                print(f"PID {{pid}} not found — agent may have already exited")

    print(f"\\nVerify: ps aux | grep {{pid}}")
    print(f"Verify: cat {{REGISTRY_PATH}}  # should be absent after kill")

if __name__ == "__main__":
    main()
'''
    (output / "kill_agent.py").write_text(kill_script)

    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "agent_id": agent_id,
        "port": port,
        "files_generated": [
            str(output / "kill_switch.py"),
            str(output / "graduated_response.py"),
            str(output / "kill_agent.py"),
        ],
        "next_steps": [
            "Implement _revoke_credentials() in kill_switch.py for your secrets manager",
            "Wire GraduatedResponseController into your injection detector and rate limiter",
            "Add /admin/throttle and /admin/shutdown routes using the shutdown endpoint pattern",
            "Test with: python kill_agent.py --dry-run --reason test",
            "Run a staging kill test and record time-to-termination",
        ],
    }
    print(json.dumps(report, indent=2))
    return 0


def cmd_simulate(args: argparse.Namespace) -> int:
    signals_input = [s.strip() for s in args.signals.split(",") if s.strip()]
    unknown = [s for s in signals_input if s not in SIGNALS]
    if unknown:
        print(json.dumps({
            "error": f"Unknown signals: {unknown}",
            "valid_signals": list(SIGNALS.keys()),
        }))
        return 1

    now = datetime.now(timezone.utc)
    max_level = 0
    actions = []
    autonomous_kill = False

    for sig_name in signals_input:
        sig = SIGNALS[sig_name]
        level = sig["level"]
        max_level = max(max_level, level)

        if sig.get("standalone_kill"):
            autonomous_kill = True
            actions.append({
                "signal": sig_name,
                "label": sig["label"],
                "level": 3,
                "action": "KILL (standalone — agent attempting to disable monitor)",
                "autonomous": True,
            })
            continue

        action = sig.get("auto_action", "log_and_alert")
        actions.append({
            "signal": sig_name,
            "label": sig["label"],
            "level": level,
            "action": action.upper().replace("_", " "),
            "autonomous": level >= 2,
        })

    # Check dual-signal pairs
    dual_triggered = None
    for pair in DUAL_SIGNAL_PAIRS:
        if pair[0] in signals_input and pair[1] in signals_input:
            dual_triggered = pair
            autonomous_kill = True
            max_level = 3
            break

    final_level = max_level
    final_action = LEVEL_ACTIONS[final_level]

    result = {
        "signals_evaluated": signals_input,
        "signal_details": actions,
        "dual_signal_triggered": dual_triggered,
        "final_level": final_level,
        "final_action": final_action,
        "autonomous_kill": autonomous_kill,
        "verdict": (
            "LEVEL 3 — AUTONOMOUS KILL. Two independent high-confidence signals confirmed."
            if autonomous_kill else
            f"LEVEL {final_level} — {final_action}"
        ),
    }

    print(json.dumps(result, indent=2))
    return 1 if autonomous_kill else 0


def cmd_test(args: argparse.Namespace) -> int:
    registry_path = Path(args.registry)
    if not registry_path.exists():
        print(json.dumps({
            "result": "FAIL",
            "reason": f"Registry not found at {args.registry}",
            "recommendation": "Agent is not running or kill switch was never registered at startup",
        }))
        return 1

    registry = json.loads(registry_path.read_text())
    checks = []

    checks.append({
        "check": "registry_exists",
        "pass": True,
        "detail": f"Registry found with agent_id: {registry.get('agent_id')}",
    })
    checks.append({
        "check": "pid_recorded",
        "pass": "pid" in registry,
        "detail": f"PID: {registry.get('pid', 'MISSING')}",
    })
    checks.append({
        "check": "credentials_listed",
        "pass": bool(registry.get("credentials_to_revoke")),
        "detail": f"Credentials: {registry.get('credentials_to_revoke', [])}",
    })
    checks.append({
        "check": "shutdown_endpoint_defined",
        "pass": bool(registry.get("shutdown_endpoint")),
        "detail": f"Endpoint: {registry.get('shutdown_endpoint', 'MISSING')}",
    })

    import os
    pid = registry.get("pid")
    pid_alive = False
    if pid:
        try:
            os.kill(pid, 0)
            pid_alive = True
        except (ProcessLookupError, PermissionError):
            pass
    checks.append({
        "check": "agent_process_alive",
        "pass": pid_alive,
        "detail": f"PID {pid} {'is running' if pid_alive else 'not found'}",
    })

    all_passed = all(c["pass"] for c in checks)
    report = {
        "registry_path": str(registry_path),
        "dry_run": args.dry_run,
        "checks": checks,
        "result": "PASS" if all_passed else "FAIL",
        "recommendation": (
            "Kill switch is registered and agent is alive. "
            "Run a staging termination test to verify end-to-end."
            if all_passed else
            "One or more checks failed — kill switch is not fully operational."
        ),
    }

    if not args.dry_run and all_passed:
        report["note"] = (
            "Live test not performed by this tool — "
            "run kill_agent.py --dry-run in staging to test termination."
        )

    print(json.dumps(report, indent=2))
    return 0 if all_passed else 1


def cmd_audit(args: argparse.Namespace) -> int:
    service_path = Path(args.service_path)
    if not service_path.exists():
        print(json.dumps({"error": f"Path not found: {args.service_path}"}))
        return 1

    py_files = list(service_path.rglob("*.py"))
    all_code = ""
    for f in py_files:
        try:
            all_code += f.read_text(errors="ignore")
        except Exception:
            pass

    def pattern_found(patterns: list[str]) -> bool:
        return any(re.search(p, all_code, re.IGNORECASE) for p in patterns)

    checks = [
        {
            "control": "KSW-01: Kill switch implementation found",
            "pass": pattern_found(KILL_SWITCH_PATTERNS),
            "severity": "CRITICAL",
            "fix": "Run: agent.py scaffold --agent-id <name> to generate kill_switch.py",
        },
        {
            "control": "KSW-01: Agent registers at startup",
            "pass": pattern_found(REGISTRATION_PATTERNS),
            "severity": "CRITICAL",
            "fix": "Call kill_switch.register() in your app startup / lifespan handler",
        },
        {
            "control": "KSW-01: Protected shutdown endpoint defined",
            "pass": pattern_found(ENDPOINT_PATTERNS),
            "severity": "HIGH",
            "fix": "Add /admin/shutdown route with admin token verification",
        },
        {
            "control": "KSW-01: Throttle mechanism present",
            "pass": pattern_found(THROTTLE_PATTERNS),
            "severity": "HIGH",
            "fix": "Implement throttle() in kill switch and check is_throttled() in tool executor",
        },
    ]

    passed = sum(1 for c in checks if c["pass"])
    score = round((passed / len(checks)) * 100)
    gaps = [c for c in checks if not c["pass"]]

    report = {
        "service_path": str(service_path),
        "python_files_scanned": len(py_files),
        "kill_switch_readiness_score": score,
        "checks": checks,
        "gaps": gaps,
        "verdict": (
            "Kill switch controls present — verify with: agent.py test"
            if score == 100 else
            f"INCOMPLETE — {len(gaps)} kill switch control(s) missing"
        ),
    }
    print(json.dumps(report, indent=2))
    return 0 if score == 100 else 1


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="AI Agent Kill Switch and Graduated Response Agent",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", required=True)

    sc = sub.add_parser("scaffold", help="Generate kill switch files for an agent service")
    sc.add_argument("--agent-id", required=True, help="Agent identifier (e.g. ew-agent)")
    sc.add_argument("--port", type=int, default=8001, help="Agent's HTTP port")
    sc.add_argument("--output", default="./kill_switch_generated/", help="Output directory")

    si = sub.add_parser("simulate", help="Simulate signal combinations and show which level fires")
    si.add_argument("--signals", required=True,
                    help=f"Comma-separated signals. Valid: {', '.join(SIGNALS.keys())}")

    te = sub.add_parser("test", help="Test kill switch registration against a running agent")
    te.add_argument("--registry", required=True, help="Path to kill_registry.json")
    te.add_argument("--dry-run", action="store_true", help="Check only, do not trigger")

    au = sub.add_parser("audit", help="Audit a service directory for kill switch controls")
    au.add_argument("--service-path", required=True, help="Path to the agent service directory")

    args = parser.parse_args()
    dispatch = {
        "scaffold": cmd_scaffold,
        "simulate": cmd_simulate,
        "test": cmd_test,
        "audit": cmd_audit,
    }
    return dispatch[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
